# Form implementation generated from reading ui file 'analysis_mode.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AnalysisMode(object):
    def setupUi(self, AnalysisMode):
        AnalysisMode.setObjectName("AnalysisMode")
        AnalysisMode.resize(480, 300)
        self.centralwidget = QtWidgets.QWidget(parent=AnalysisMode)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.degradeTimeInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.degradeTimeInput.setObjectName("degradeTimeInput")
        self.verticalLayout.addWidget(self.degradeTimeInput)
        self.fileNameInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.fileNameInput.setObjectName("fileNameInput")
        self.verticalLayout.addWidget(self.fileNameInput)
        self.maxStabConcInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.maxStabConcInput.setObjectName("maxStabConcInput")
        self.verticalLayout.addWidget(self.maxStabConcInput)
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        AnalysisMode.setCentralWidget(self.centralwidget)

        self.retranslateUi(AnalysisMode)
        QtCore.QMetaObject.connectSlotsByName(AnalysisMode)

    def retranslateUi(self, AnalysisMode):
        _translate = QtCore.QCoreApplication.translate
        AnalysisMode.setWindowTitle(_translate("AnalysisMode", "Analysis Mode"))
        self.degradeTimeInput.setPlaceholderText(_translate("AnalysisMode", "Degrade Time (hours)"))
        self.fileNameInput.setPlaceholderText(_translate("AnalysisMode", "File Name"))
        self.maxStabConcInput.setPlaceholderText(_translate("AnalysisMode", "Maximum Stabilizer Concentration (default 0.2)"))
        self.saveButton.setText(_translate("AnalysisMode", "Save to Excel"))
