# Form implementation generated from reading ui file 'calculator_mode.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CalculatorMode(object):
    def setupUi(self, CalculatorMode):
        CalculatorMode.setObjectName("CalculatorMode")
        CalculatorMode.resize(480, 300)
        self.centralwidget = QtWidgets.QWidget(parent=CalculatorMode)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.expectedLifeTimeInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.expectedLifeTimeInput.setObjectName("expectedLifeTimeInput")
        self.verticalLayout.addWidget(self.expectedLifeTimeInput)
        self.maxStabConcInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.maxStabConcInput.setObjectName("maxStabConcInput")
        self.verticalLayout.addWidget(self.maxStabConcInput)
        self.decimalPlacesInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.decimalPlacesInput.setObjectName("decimalPlacesInput")
        self.verticalLayout.addWidget(self.decimalPlacesInput)
        self.resultDisplay = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.resultDisplay.setObjectName("resultDisplay")
        self.verticalLayout.addWidget(self.resultDisplay)
        self.calculateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculateButton.setObjectName("calculateButton")
        self.verticalLayout.addWidget(self.calculateButton)
        CalculatorMode.setCentralWidget(self.centralwidget)

        self.retranslateUi(CalculatorMode)
        QtCore.QMetaObject.connectSlotsByName(CalculatorMode)

    def retranslateUi(self, CalculatorMode):
        _translate = QtCore.QCoreApplication.translate
        CalculatorMode.setWindowTitle(_translate("CalculatorMode", "Calculator Mode"))
        self.expectedLifeTimeInput.setPlaceholderText(_translate("CalculatorMode", "Expected Life Time (hours)"))
        self.maxStabConcInput.setPlaceholderText(_translate("CalculatorMode", "Max Stabilizer Concentration (default 0.2)"))
        self.decimalPlacesInput.setPlaceholderText(_translate("CalculatorMode", "Decimal Places"))
        self.calculateButton.setText(_translate("CalculatorMode", "Calculate"))
