# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 350)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calculatorModeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculatorModeButton.setObjectName("calculatorModeButton")
        self.verticalLayout.addWidget(self.calculatorModeButton)
        self.analysisModeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.analysisModeButton.setObjectName("analysisModeButton")
        self.verticalLayout.addWidget(self.analysisModeButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PVC Degradation Analysis"))
        self.calculatorModeButton.setText(_translate("MainWindow", "Calculator Mode"))
        self.analysisModeButton.setText(_translate("MainWindow", "Analysis Mode"))
